### PR TITLE
use new modules api

### PR DESCRIPTION
**Pull request by Dhaulagiri**
Went smoothly with the exception of two imports that the codemod doesn't know about:

* `Ember.RouterDSL` - It seems like this could be added to the dataset used to polyfill back to the old globals imports as [`@ember/routing` includes several other similar modules](https://github.com/ember-cli/ember-rfc176-data#emberrouting)
* `Ember._ProxyMixin` - This is private and therefore my understanding is it won't be included in the new modules api, but I'm not sure what this means in practice here

### CODE REVIEW

**Comment by bantic** [comment]
@Dhaulagiri You're a saint.

Have you smoke-tested this build against any running apps?

I don't remember offhand what `Ember._ProxyMixin` does, but I am sure there's a refactor to get rid of it from the torii session service. 
Probably the same for `Ember.RouterDSL` although that might need more finesse.

**Comment by Dhaulagiri** [comment]
It's a little tricky testing our torii setup locally, but I'll try to do that to at least sanity test that things are working as expected.

With respect to the two modules we are talking about, at this point there nothing requiring that the new modules imports be used so there is time to refactor these use cases.

**Comment by Dhaulagiri** [comment]
Ha, well...our app didn't boot at first. The reason was that I accidentally also converted files in this addon's `/app` directory which is a no-no with this since we can't control how an app is going to transpile files in that directory (in fact our app is still using ember-cli-babel 5).  Once I undid that change things worked as expected.

**Comment by Dhaulagiri** [comment]
@bantic got a bit sidetracked with real life but I did try this in our app and authing with a 3rd party service does work as it did before.

(Also included a commit to update us to ember-cli 2.16 here as well)

**Comment by mixonic** [comment]
@Dhaulagiri this looks great :-) Thank you for taking this on.

**Pull request merged**
