### PR TITLE
lookup torii service instead of using get

### PR DESCRIPTION
**Pull request by Dhaulagiri**
This should fix issues folks are having with 2.13 and get the test suite passing again

Fixes https://github.com/Vestorly/torii/issues/353
Fixes https://github.com/Vestorly/torii/issues/349

### CODE REVIEW

**Comment by jmonster** [comment]
👍 💯 🚀 

if I could merge this I would merge it so ⏩ fast.

**Comment by jdurand** [comment]
For the record, I pulled this to my fork and have this running in a production app.

**Comment by bantic** [comment]
Yes! Thank you @Dhaulagiri

**Comment by bantic** [comment]
This is released on v0.8.3.

**Comment by j-chaidez** [comment]
You are awesome! Thanks a ton.

**Pull request merged**
