### PR TITLE
Ember 2.13 - Fix deprecated usage of router.router

### PR DESCRIPTION
**Pull request by Dhaulagiri**
https://emberjs.com/deprecations/v2.x/#toc_ember-router-router-renamed-to-ember-router-_routermicrolib

### CODE REVIEW

**Comment by Dhaulagiri** [comment]
The failure happening agains Ember 2.13 doesn't appear related to my changes as I see the same failure locally against master.

**Comment by mwpastore** [comment]
@Dhaulagiri There is more work to do. [Here](https://github.com/mwpastore/torii/commit/d4edbda3ed4a58aa42cacd29aac0847df5b7143e)'s my WIP that seems to be mostly functional.

**Comment by Dhaulagiri** [comment]
@mwpastore nice! i hadn't noticed that other usage.  If you want to open a PR with your change I'm happy to close mine.

**Comment by Dhaulagiri** [comment]
@mwpastore your fix looks good to me, we just need to make sure it is backwards compatible with older versions of ember that this addon still supports.  If try running your change against ember 1.12 or 1.13 you'll see the tests fail.

**Comment by Dhaulagiri** [comment]
got everything passing but it's becoming a little brittle so I'll defer to @bantic on whether or not we want to do this or wait until we have a little more time to refactor things.

**Comment by bantic** [comment]
@Dhaulagiri thank you!

**Comment by bantic** [comment]
released on v0.8.4

**Pull request merged**
