### PR TITLE
Google OAuth2 provider update

### PR DESCRIPTION
**Pull request by jfschaff**
Hi, this fixes what I mentioned in issue #331.

I implemented a new provider, named 'google-oauth2-bearer-v2', which uses Google's most recent authentication URL. It also performs an extra step: once a token is received, it is first validated by a second request to another URL (see [that link](https://developers.google.com/identity/protocols/OAuth2UserAgent#tokeninfo-validation) for more details).

I tested this provider with Ember Simple Auth, and fixed a couple of initial issues. I also included an example use of this provider in the example application, and instructions on how to set the provider.

### CODE REVIEW

**Comment by balinterdi** [comment]
Build broken because of https://github.com/Vestorly/torii/pull/340 . Merging in that PR would probably fix this one, too.

**Comment by Subtletree** [comment]
Can this be merged now that #340 is fixed in  #344?

**Comment by bantic** [comment]
@jfschaff Thanks for providing this. I'm going to rebase it and then merge. 👍

**Comment by bantic** [comment]
@jfschaff thanks for this PR! I rebased and squashed into #372.

**Pull request closed without merging**
