### PR TITLE
Fix sessionServiceName to b dynamic in authenticated and application routes

### PR DESCRIPTION
**Pull request by bmeyers22**
The sessionServiceName was hard coded to session in some of the files, namely the AuthenticateRouteMixin and ApplicationRouteMixin.  I imported configuration so it is dynamic with the environment.js file.

### CODE REVIEW

**Comment by mwpastore** [comment]
+1

**Comment by mwpastore** [comment]
Missed one. Here's a patch to the pull request:

```
--- a/lib/torii/routing/authenticated-route-mixin.js
+++ b/lib/torii/routing/authenticated-route-mixin.js
@@ -14,14 +14,14 @@ export default Ember.Mixin.create({
   },
   authenticate: function (transition) {
     var route = this;
-    var isAuthenticated = this.get('session.isAuthenticated');
-    if (isAuthenticated === undefined) {
+    var session = this.get(configuration.sessionServiceName);
+    if (session.isAuthenticated === undefined) {
       this[configuration.sessionServiceName].attemptedTransition = transition;
       return this[configuration.sessionServiceName].fetch()
         .catch(function() {
           return route.accessDenied(transition);
         });
-    } else if (isAuthenticated) {
+    } else if (session.isAuthenticated) {
       // no-op; cause the user is already authenticated
       return Ember.RSVP.resolve();
     } else {
```

**Comment by bmeyers22** [comment]
Put in the fixes, I can make  new fork and have the changes all in one commit if desired

**Comment by mixonic** [comment]
@bmeyers22 what happened here? Not actually an issue?

**Comment by mwpastore** [comment]
It's definitely still an issue and this pull request (with my patch) definitely solves it!

**Comment by mixonic** [comment]
@mwpastore there is no actual code to merge in this PR. I believe @bmeyers22 is moving the effort to https://github.com/Vestorly/torii/pull/228.

**Comment by bmeyers22** [comment]
@mixonic closed in favor of #228

**Comment by mwpastore** [comment]
Didn't see that one. Great!

**Pull request closed without merging**
