### PR TITLE
Replace `Ember.K` usage with JavaScript syntax

### PR DESCRIPTION
**Pull request by locks**

### CODE REVIEW

**Comment by locks** [comment]
Hi, are all the failing tests related to my PR? I'm not familiar with the test suite, so I need a bit of help unpacking the failures.

**Comment by locks** [comment]
Bump, can some kick the CircleCI for me?

**Comment by leizhao4** [comment]
Bump. Ember 2.12 Beta has deprecated `Ember.K` and we get lots of deprecation warnings. Could someone merge this pull request and release a new version? Thanks!

**Comment by mixonic** [comment]
Kicked 😬 let's see

**Comment by leizhao4** [comment]
Looks like the same Node 0.10/0.12 incompatibility issue I had with [ember-cli-deploy-build](https://github.com/ember-cli-deploy/ember-cli-deploy-build/pull/35). `broccoli-persistent-filter` -> `async-disk-cache ^1.2.1` -> `username ^2.3.0` no longer supports Node 0.12.

**Comment by bantic** [comment]
closed in a rebased version of this PR ( #346 )

**Pull request closed without merging**
